### create requests - POST /exercises
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squat",
    "reps": 10,
    "weight": 30,
    "unit": "lbs",
    "date": "06-24-21"
}

### create
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Dead lift",
    "reps": 20,
    "weight": 1005,
    "unit": "kgs",
    "date": "01-01-93"
}

### create
POST http://localhost:3000/exercises HTTP/1.1
Content-Type: application/json

{
    "name": "Push ups",
    "reps": 3000,
    "weight": 1,
    "unit": "lbs",
    "date": "05-29-25"
}

### retrieve requests - GET /exercises
GET http://localhost:3000/exercises HTTP/1.1

### update requests - PUT /exercises/:id
PUT http://localhost:3000/exercises/6197011a3a056d3937868fd0 HTTP/1.1
Content-Type: application/json

{
    "name": "big diccus squats",
    "reps": 100000,
    "weight": 300000,
    "unit": "kgs",
    "date": "11-26-12"
}

### delete requests - DELETE /exercises/:id
DELETE http://localhost:3000/exercises/6197011a3a056d3937868fd0 HTTP/1.1

###
DELETE http://localhost:3000/exercises/6197012a3a056d3937868fd2 HTTP/1.1

###
DELETE http://localhost:3000/exercises/619701313a056d3937868fd4 HTTP/1.1