### create requests - POST /exercises
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squat",
    "reps": 10,
    "weight": 30,
    "unit": "lbs",
    "date": "06-24-21"
}

### create
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Dead lift",
    "reps": 20,
    "weight": 1005,
    "unit": "kgs",
    "date": "01-01-93"
}

### create
POST http://localhost:3000/exercises HTTP/1.1
Content-Type: application/json

{
    "name": "Push ups",
    "reps": 3000,
    "weight": 1,
    "unit": "lbs",
    "date": "05-29-25"
}

### retrieve requests - GET /exercises
GET http://localhost:3000/exercises HTTP/1.1

### update requests - PUT /exercises/:id
PUT http://localhost:3000/exercises/6196edfb57f2baaa79204235 HTTP/1.1
Content-Type: application/json

{
    "name": "8888",
    "reps": 100,
    "weight": 300,
    "unit": "kgs",
    "date": "11-25-12"
}

### delete requests - DELETE /exercises/:id
DELETE http://localhost:3000/exercises/6196edfa57f2baaa79204233 HTTP/1.1

###
DELETE http://localhost:3000/exercises/6196edfb57f2baaa79204235 HTTP/1.1

###
DELETE http://localhost:3000/exercises/6196edfc57f2baaa79204237 HTTP/1.1